### PR TITLE
Manual sync now works in offline mode

### LINKED ISSUE #76: Bug: When working offline, Upload/download buttons don't do anything
To reproduce:
- In settings, turn Work Offline "On"
- Add a new task
- Tap the sync button
- From the prompt, choose "Upload changes". Wait--nothing happens.
- Go back into Settings, and turn Work Offline "Off"
- The Manual sync dialog shows up and you can download/upload.

This is confusing.  We should do 1 of 2 things to make it less confusing:
1. Hide the refresh button entirely while Work Offline is set to on. Alternatively we can make it a "Go Online" button.
2. Make the upload/download buttons actually upload or download while Work Offline is set to On, if the user taps refresh.

### PR DESCRIPTION
**Pull request by chuckbjones**
Fixes #76

### CODE REVIEW

**Comment by ginatrapani** [comment]
Works great! In the simulator, I was already logged into Dropbox and the manual sync worked even with Work Offline checked. Fantastic.

But then I decided to test issue #80, and tapped Log out of Dropbox, and the app crashed. Then I tried running it again (this is all in the simulator), and it hangs in main(). Now I can't get the app to run at all in any simulator.

So the good news is we can repro the logout problem in the simulator, but the bad news is this patch may have made it worse... are you seeing this?

**Comment by chuckbjones** [comment]
I'm actually having a harder time reproducing the crash now. We're getting a EXC_BAD_ACCESS error, which usually means we are trying to access an object that has already been destroyed. I haven't figured out where it is though.

**Comment by mcguiresm** [comment]
Ok it seems I've been able to successfully reproduce the issue in the simulator.
1.) Start the iOS Simulator
2.) Login to Dropbox
3.) Quit the Simulator
4.) Start the Simulator (It should have you logged in to Dropbox already)
5.) Tap Settings Icon
6.) Tap Logout of Dropbox
7.) Crash

**Comment by mcguiresm** [comment]
The steps that I wrote are the same on my iPhone 4S too.  After the app crashes and you sign back in to Dropbox, if you try to go to logout of Dropbox it works.  It seems that it only happens after your are logged in to Dropbox and close out of the app completely (not just hit the home button) and open the app back up, then tap logout out of Dropbox that it crashes

**Comment by ginatrapani** [comment]
Okay, I think we're all going crazy. I cleaned and rebuilt, and tried this a bunch of times, and at first I was able to repro the crash, but now I'm not, even following @bigbash's steps one by one. So I'm going to merge this patch, b/c it's an improvement to the Work Offline bits, and we'll keep an eye out for this crash again.

**Pull request closed without merging**
