### PR TITLE
Handle missing/deleted files better

### PR DESCRIPTION
**Pull request by chuckbjones**
Hopefully this should fix the bug mentioned [here](https://github.com/ginatrapani/todo.txt-touch-ios/pull/122#issuecomment-4227905) in #122.

My internets have been acting wonky today, so it has been difficult to test.
1. We now handle the case where Dropbox tells us that a file exists but has been deleted. We treat it as if the file never existed.
2. We now properly consider a non-existent local copy of done.txt as "not modified" so we won't try to upload it.
3. Fixed a minor issue where we were displaying "Error downloading" after failing to upload.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Looking good! Okay, so this takes care of deleted/nonexistent done.txt files, so I'm going to merge it.

On further testing, I found a bug with logging in and out of Dropbox. To reproduce:

Launch app, auth on Dropbox, add a few tasks. 
Mark all or some of the tasks complete, and archive them to done.txt.
In Settings, log out of Dropbox. Sometimes (but not all times) I get an EXC_BAD_ACCESS crash here.

If not, restart your simulator with the app, and instead of displaying the todo.txt file, you see the done.txt file's contents (crossed out), with a SIGABRT signal.

Let me know if you're not seeing this problem, and thanks again for working on this Chuck.

**Comment by chuckbjones** [comment]
I can reproduce this, but I have no idea what's causing it. I'll keep looking at it. Can you reproduce it on a device, or is it only happening on the simulator?

**Comment by ginatrapani** [comment]
Yes, I can reproduce same behavior on the device as well. Something wacky's going on during Log Out.

**Comment by chuckbjones** [comment]
Should be fixed in #127. I'm still not sure why, but when replacing the main view with the login screen, release was being called one to many times. I avoided that issue by popping the login screen up as a modal view instead, so we never need to remove the main view at all.

A second issue was happening after logging in. We were syncing when the app was reactivated and then after processing the login event, so two sync processes were occurring simultaneously. I removed the second call since it was not needed for Dropbox. We may need to add it back in for other services, though. I also refactored the Dropbox sync logic so that if we do have simultaneous syncs occurring, it should not cause any errors.

**Pull request merged**
