### PR TITLE
Turn off extending under top and bottom bars on the new task view.

### LINKED ISSUE #187: Unable to add tasks using iOS 7 on iPhone 5
I upgraded to iOS 7 yesterday and tried using ToDoTXT as I do every day - it appears that entering tasks doesn't work anymore.  I'm unable to see the text as I type it on the Add Tasks screen.  I did try uninstalling/reinstalling ToDoTXT after iOS 7 was upgraded but the problem still exists and at the moment I'm unable to use ToDoTXT for anything other than viewing tasks I have already entered.

### PR DESCRIPTION
**Pull request by brendonjustin**
Fixes #187. Will not fix the issue on other views, though I think this is the only one affected.

Yikes.

### CODE REVIEW

**Comment by ginatrapani** [comment]
I think the same issue is causing #185 as well. Could we fix it in that view too?

**Comment by ginatrapani** [comment]
Merged in 7e2df2491f36792bd88e04b0ca0db9a3c0acc3dc (had to resolve a minor conflict in the rebase)

**Comment by dmd** [comment]
This is not a complete fix.

This is NOT fixed in the new version.
To reproduce:
1. Enter task.
 (Task shows properly.)
2. Tap the task.
 (Task shows properly for editing - this IS fixed.)
3. Tap 'save'.
 (Task is now HIDDEN underneath the 'task details' title.)

**Comment by brendonjustin** [comment]
Is that the only other instance of the issue?

**Comment by ginatrapani** [comment]
No, the "hidden under the top bar" issue seems to occur throughout the app. Logged more reproducible cases of it in ticket #185

**Pull request merged**
