### PR TITLE
Add split view, big reorganization, and some refactoring

### PR DESCRIPTION
**Pull request by brendonjustin**
- Includes a split view implementation on iPad for filtering tasks, still limited to landscape mode like my last PR. The app should look nearly the same as before, aside from the new split view.
- Task cells are laid out via Auto Layout in code.
- Most of the files have been reorganized and most xibs have been consolidated into the storyboards.
- Thanks to the refactoring and move to Storyboards & Auto Layout, a significant amount of code has been removed.
- ReactiveCocoa has been added as a dependency via git submodule. It is used in a few places.
- Updated the Dropbox SDK to 1.3.4

Aspects you may want to change:
- The fonts for the priority and age labels may have changed
- The splash screen displayed when the user has to log in to Dropbox could be laid out a bit better
- The help popover when editing a task on iPad could look better

None of those should be difficult, but I think they come down to taste so I'm leaving them for you to change as you see fit.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Wow, thank you very much. I've been in Android mode this past week but will take a look at this tonight.

**Comment by rhussmann** [comment]
I believe autolayout requires iOS6. Is the app already enforcing iOS6 as a baseline?

**Comment by brendonjustin** [comment]
The app currently on the store supports 4.3 and up. Most people are on iOS 6 now, so I think targeting 6 will be fine.

**Comment by ginatrapani** [comment]
Yep, targeting iOS6 is fine. Brendon there's obviously a ton of work here, thank you. Testing it out in the simulator, there are a lot of layout/visual bugs (missing task text, priority misalignment, date font size weirdness). Here's a screenshot:

screenshot_jul_6_9_04_pm

Can we get the task list layout and typography to look exactly like it did before?

**Comment by brendonjustin** [comment]
Can you upload that todo.txt file? I don't get any layout issues with mine.

**Comment by ginatrapani** [comment]
Sure thing, this is a demo file I use for testing/screenshots. The contents:

`
2013-06-30 Refill wineskin @Village
(B) 2013-07-01 Schedule chain mail fitting @Castle +Battle
(C) 2013-06-20 Sharpen sword +Battle
2013-06-29 Reinforce battlements @Castle +Battle
2013-07-01 Saddle the horses @Barn
x 2013-07-02 2013-06-28 Bridge the moat @Castle
(A) 2013-07-02 Take the throne @Castle +RuleTheKingdom
`

**Comment by brendonjustin** [comment]
How's that? I think I got everything.

**Comment by ginatrapani** [comment]
Much better! Still getting a little bit of weirdness where the date text and the task text run into one another. Screenshot:

ios simulator screen shot sunday 7 7 13 jul 7 11 26 26 pm

Contents of this todo.txt file:

`
2013-06-01 Pay debts +LannisterName
(C) 2013-03-01 Chastise Joffrey
(B) 2013-06-15 Refill wineskin
(A) 2013-04-27 Schedule chain mail fitting +SelfPreservation
(A) 2013-03-28 Sharpen sword +SelfPreservation @Castle
(A) 2012-08-12 Reinforce battlements +BaratheonOffensive +SelfPreservation
(B) 2013-02-12 Stock up on flagons of Dornish wine
2013-07-07 This is a test of a very long task text that wraps around when you type it into the "Add Task" screen on an iOS 6.1 iPad simulator on my MacBook Pro
`

Also, if I select the last task and try to prioritize it, the app crashes.

`
2013-07-07 23:28:12.662 Todo.txt Touch[25908:c07] didTapPrioritizeButton called
2013-07-07 23:28:15.316 Todo.txt Touch[25908:c07] -[TaskViewController priorityWasSelected::]: unrecognized selector sent to instance 0xa2aead0
2013-07-07 23:28:15.316 Todo.txt Touch[25908:c07] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TaskViewController priorityWasSelected::]: unrecognized selector sent to instance 0xa2aead0'
*** First throw call stack:
(0x1b23012 0x1948e7e 0x1bae4bd 0x1b12bbc 0x1b1294e 0x195c705 0x165fc 0x195c705 0xe982c0 0x10d4a64 0x195c705 0xe982c0 0xe98258 0xf59021 0xf5957f 0xf586e8 0xec7cef 0xec7f02 0xea5d4a 0xe97698 0x250adf9 0x250aad0 0x1a98bf5 0x1a98962 0x1ac9bb6 0x1ac8f44 0x1ac8e1b 0x25097e3 0x2509668 0xe94ffc 0x483d 0x2665 0x1)
libc++abi.dylib: terminate called throwing an exception
(lldb) 
`

**Comment by brendonjustin** [comment]
It should layout correctly now.

We may have hit a bug with UITextView's handling of attributed text; see c0cc207 for details.

**Comment by brendonjustin** [comment]
ping?

**Comment by ginatrapani** [comment]
Apologies for my absence! Will be testing tonight/this weekend. Thanks for the nudge.

**Comment by ginatrapani** [comment]
@brendonjustin This looks great! I love it and I want to merge it. 

Problem is, my master branch and this pull have gotten far out of sync. I attempted to rebase this branch on master and it was long and painful and the result created build failures. You can see that branch here:

https://github.com/ginatrapani/todo.txt-ios/tree/filter2

Can you rebase this branch on top of the current state of master, then squash all your commits into a single commit, with a commit message that just outlines the key points around the change? Thank you so much!

**Comment by brendonjustin** [comment]
Superceded by #171

**Pull request closed without merging**
