### PR TITLE
Swiping in search screen now completes correct task.

### LINKED ISSUE #37: Swipe to Complete doesn't work in search results
To reproduce: Search for a todo, then swipe to complete. Nothing happens.

### PR DESCRIPTION
**Pull request by rhussmann**
Closes #37

### CODE REVIEW

**Comment by rhussmann** [comment]
I like to code. And I really want to use todo.txt on my phone =o)

**Comment by ginatrapani** [comment]
Lucky us! Just added your 4S to the provisioning profile and reuploaded to TestFlight, so you should be able to install it now. Let me know if not.

**Comment by rhussmann** [comment]
Thanks! I have a dev certificate, though, so it's not vital I be in TestFlight. I can install from my machine.

**Comment by rhussmann** [comment]
But if you know anyone that wants to give away a sexy, 13" Macbook air, make sure you give them my info =o)

**Comment by ginatrapani** [comment]
Hehe, will do. :)

**Pull request closed without merging**
