### PR TITLE
Swipe 2 complete

### PR DESCRIPTION
**Pull request by mcguiresm**
Added swipe to complete

### CODE REVIEW

**Comment by ginatrapani** [comment]
Thanks Shawn! I'm out of town right now but will get to this Monday or
Tuesday.

Sent from my mobile
On Oct 16, 2011 4:57 PM, "Shawn McGuire" <
reply@reply.github.com>
wrote:

**Comment by ginatrapani** [comment]
Hey Shawn,

This is a great start. I've been testing it in the simulator, and have had a few app crashes after I swipe and click on the Complete button. Sometimes it works and sometimes it doesn't. I think the commonality is the application crashes whenever the task I try to swipe to complete has a project or context in it. Can you reproduce that problem?

I'm new to debugging iOS apps, so let me know what info you need from the debugger to figure out what's going wrong.

**Comment by chuckbjones** [comment]
@bigbash, remove line 322: `[task release];`. Since you don't call retain when setting the Task object, you don't need to release it either. This is what is causing the crash.

**Comment by ginatrapani** [comment]
@bigbash @chuckbjones Yes, removing line 322 resolves the app crashes. Excellent!

One other problem: after you swipe to complete a task, your todo.txt file doesn't sync back to Dropbox the way it does if you tap a task and tap Complete from the menu.

So if you tap to complete a task then refresh, what you marked as complete returns as incomplete.

**Comment by chuckbjones** [comment]
Add `[todo_txt_touch_iosAppDelegate pushToRemote];` to the end of the method.

**Comment by ginatrapani** [comment]
That did it, thnx Chuck! Merged.

**Comment by mcguiresm** [comment]
@chuckbjones you sir are an iOS genius :) Thanks for all your help and pointers

**Pull request closed without merging**
