### PR TITLE
Restore network logic that didn't use ReactiveCocoa

### PR DESCRIPTION
**Pull request by brendonjustin**
I think I made a mistake using ReactiveCocoa before, so I'm seeing about removing it and mostly restoring the previous syncing logic.

If you agree, I can remove it as a dependency entirely without much trouble in another PR.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Hey Brendon, sorry I've been away from this for so long. If you're still up for this, I'd love to know more - what made you decide to use ReactiveCocoa in the first place and why you think you made a mistake. That would help me decide if it's worth it - seems like it would, at least, simplify the codebase by removing the dependency.

**Comment by brendonjustin** [comment]
I can write (some) logic faster using ReactiveCocoa than without, so I am usually inclined to use it. I don't think it was a good idea in this case because of RAC's steep learning curve. If I didn't know it or plan on learning it, I wouldn't want it in a project that I maintain. A strange looking library probably deters potential contributors, too.

**Comment by ginatrapani** [comment]
Yep, makes sense. I'd definitely merge a PR that removed it. Thanks for helping us keep things simple.

**Comment by brendonjustin** [comment]
I don't know if I'll have time to do this soon, so don't wait around for it.

**Comment by ginatrapani** [comment]
Understood. Thanks Brendon.

**Comment by brendonjustin** [comment]
Superseded by #225

**Pull request closed without merging**
