### PR TITLE
Split view for filtering on iPad (issue #81)

### PR DESCRIPTION
**Pull request by brendonjustin**
Straightforward implementation of the issue #81 mockup.

Some notes:
- The filter view is not yet available in portrait on iPad or at all on iPhone.
- The deployment target is set to iOS 5.
- I re-organized the project structure to use groups (and folders) more.

Edited for specificity.

### CODE REVIEW

**Comment by ginatrapani** [comment]
_GASP_
So exciting! Thank you! Can't wait to try it.

**Comment by ginatrapani** [comment]
This is a great start! So far testing is going well, especially with that last commit. One bug: the app crashes whenever you tap the settings button.

**Comment by brendonjustin** [comment]
That was a silly mistake. Fixed.

**Comment by ginatrapani** [comment]
So nice! Looking great. One other minor bug: Lengthy task text runs off to the side of the list view, and in the Task Details view. Looks like we just have to adjust the wrap margin for them when the iPad is in landscape.

**Comment by ginatrapani** [comment]
Another minor bug: If you've got a context or project that only has one task associated with it, then you filter by that project or context and delete the task, you get the "Your todo.txt file is empty" message, which isn't really true -- it's just that there are no tasks which match the filter.

Is the list view aware that it's being filtered? If so, let's display a "No tasks match [context/project]."

**Comment by brendonjustin** [comment]
Another way to get that situation is to filter such that no one task has all of the selected contexts, so there are no results. I'll see how I'd go about showing a different message.

(It is aware when it is being filtered.)

Regarding text layout, I'd like to bump the minimum target to iOS 6.0 and use Auto Layout. It might eliminate the FlexiTaskCell subclasses, and I've got my eye on adapting for iOS 7 in the future.

**Comment by ginatrapani** [comment]
I'm fine with an iOS 6.0 minimum target, and using Auto Layout. Also happy about adapting for iOS 7. Hooray!

**Comment by ginatrapani** [comment]
I see the informative message, which is great, but it's all I see--I'm not seeing the list of tasks even when nothing is selected.

**Comment by brendonjustin** [comment]
I'm making some changes to the TaskBag protocol so I can make the split view work well. I might be a few days.

**Comment by ginatrapani** [comment]
Cool, thanks for the update.

**Comment by brendonjustin** [comment]
I misjudged the changes I'd need to make. Other than longer tasks not being sized quite correctly, the split view should work now.

**Comment by brendonjustin** [comment]
Abandoning this in favor of PR #165

**Pull request closed without merging**
