### PR TITLE
Fix manual sync dialog

### PR DESCRIPTION
**Pull request by chuckbjones**
I'm not sure why this wasn't working, but it should definitely be fixed now.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Ah yes, this fix makes the manual sync dialog show up when Work Offline is set to off. Thank you.

Something is still confusing though. When you have Work Offline set to On, and tap refresh, the Manual sync dialog shows up but does nothing.

We should do 1 of 2 things to remedy that:
1. Hide the refresh button entirely while Work Offline is set to on--or perhaps make it a "Go Online" button.
2. Make the upload/download buttons actually upload or download while Work Offline is set to On, if the user taps refresh.

I prefer #2, but #1 would be okay. What do you think?

**Comment by ginatrapani** [comment]
Merged this commit, and updated the convo on issue #76. Thanks Chuck!

**Comment by chuckbjones** [comment]
Yep. The android app does the same thing (see [issue 204](https://github.com/ginatrapani/todo.txt-touch/issues/204)). I implemented it the same way for parity, but I would also prefer #2. It shouldn't be difficult to implement.

**Comment by ginatrapani** [comment]
Okay, that sounds good. Between this fix and the Dropbox revision handling, the iOS app is already ahead of Android, despite lack of context/project filtering. I guess the fear of not making it through the submission process is a good thing?! (Don't tell anyone I said that)

**Comment by MakkieJones** [comment]
What's happening with this? Using iOS.

**Pull request closed without merging**
