### PR TITLE
Add configurable open-item badge count

### PR DESCRIPTION
**Pull request by paulroub**
As discussed in #102

The option names are truncated (with ellipsis) in iPhone portrait mode, on the main settings screen only, although I believe the ShortTitle strings will be used there instead under iOS 5.  The full titles are properly displayed elsewhere and in all other resolutions.

The default is to use no badge count, as before.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Nice job on this, thanks Paul. Would it be difficult to add unit tests for this?

**Comment by paulroub** [comment]
No, really a matter of pulling the counting code out into one of the utility classes and testing that.  A refactoring that should probably happen, anyway... too much "core" code in the UI classes as it is, at least from a testing standpoint.

**Comment by ginatrapani** [comment]
Okay, good to know. I merged it anyway b/c it was a relatively small code change with great utility, and I was excited about it. But I aim to get more disciplined about requiring tests before merging new code.

I tweaked the option copy in 5b7dcd2386305042e734d9e68641b0b23ca288c8 as well.

One more thing: Never develop on your master branch. When you start working on a feature, create a new branch freshly rebased from my master. Right now your master and my master are pretty far out of sync, which makes pull requests kind of messy. Here's a full guide on how to do it (just substitute Todo.txt for ThinkUp):

http://thinkupapp.com/docs/contribute/developers/devfromsource.html

Thanks again, this is a really nice new feature.

**Comment by paulroub** [comment]
Thanks for the heads up on branching... I spend my days working in / building a DVCS with a different view of branches, and my brain and git aren't lined up very well.

**Pull request merged**
