### PR TITLE
Flexi cell

### PR DESCRIPTION
**Pull request by rhussmann**
I've added the beginnings of supporting FlexiCells. What's the policy on licensing new files added to the project? Should I copy / paste the license already in your code, should the author line be changed? Just curious. Let me know what you think. Feel free to clone my repo to preview the change.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Hey thanks Ricky, this looks good. 

> What's the policy on licensing new files added to the project? Should I copy / paste the license already in your code, should the author line be changed?

Exactly. Right now the code is GPL, but we're going to have to dual-license GPL/MIT to release in the iTunes Store. I'll send an email out about that sometime this week to you, Shawn, and Charles. For now, just copy/paste the GPL license header and change the filename and author line.

If you want, I can make that update and merge this pull request as is. Or I can wait if there's more you want to add to it. Let me know either way.

**Comment by rhussmann** [comment]
Yeah, go ahead and merge and make the update, if you would. I'll continue to tweak the FlexiCell stuff over the week. I've also been looking into strikethrough text. It requires quite a bit of legwork, believe it or not. With great flexibility comes... great amounts of code, I guess? We shall see.

**Comment by ginatrapani** [comment]
Great, thanks Ricky. I made those changes and squashed your commits. I had a small problem though: I merged commits from @bigbash and @chuckbjones before I added yours, and since you all edited code in the same method, there's a conflict I was unable to resolve when I added your flexi-cell commit. 

Could you take a look at the rebased/squashed flexi-cell branch here? You'll see the line Xcode is complaining about. I hope/suspect this is a quick/easy fix:

https://github.com/ginatrapani/todo.txt-touch-ios/tree/flexi-cell

**Comment by chuckbjones** [comment]
In order to handle displaying search results, I added two new methods: `- (NSArray*) taskListForTable:(UITableView*)tableView` and `- (Task*) taskForTable:(UITableView*)tableView atIndex:(NSUInteger)index` They need to be used anywhere where the `tasks` array was used previously (Looks like lines 228 and 238).

**Comment by rhussmann** [comment]
Okay, I took Chuck's advice and am now using taskForTable:atIndex: as my backing task querying for cells. I'll send a separate push request for Gina's flexi-cell branch, and let her merge that back into master. Sound okay?

**Comment by ginatrapani** [comment]
Looks good, thanks Ricky & Chuck. Merged!

**Pull request closed without merging**
