### PR TITLE
Support adding multiple tasks at once.

### PR DESCRIPTION
**Pull request by brendonjustin**
Tasks are delimited by newlines during entry.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Hey Brendon,
Can we get this to work the way the Android app does -- with tasks delimited by a single, not a double, newline?

**Comment by brendonjustin** [comment]
Sure. Commits and pull request description updated.

**Comment by ginatrapani** [comment]
Fantastic, thanks! Last q: how difficult will it be to add hint text with line breaks in it to let the user know batch entry is possible? Here's what that looks like on Android:

https://lh5.ggpht.com/9bR41Wie8CRYTLfY_K3w7FRYw5h_u3bZVNDcr7gwfoy35Xd5oq49ssctI2BPqXw28xQ=h900-rw

Can we just add a newline to the placeholders.plist values? 

The multi-task hint text rotates between 5 possibilities:

```
    <string name="tasktexthint0">Draft chapter 1 +Novel @typewriter\nCall literary agent @phone</string>
    <string name="tasktexthint1">Learn to code +SelfEducation\nBuild a killer app @computer</string>
    <string name="tasktexthint2">Take the road less traveled @Woods\nMake all the difference +Life</string>
    <string name="tasktexthint3">Schedule chain mail fitting @castle\nSharpen sword +SelfPreservation</string>
    <string name="tasktexthint4">Complete weekly review +GTD\nAchieve mind like water +GTD</string>
```

**Comment by ginatrapani** [comment]
Forget I asked! I just tried it and adding a newline in the plist values (Option+Return) works. I'll do that bit. Thanks again!

**Pull request merged**
