### PR TITLE
re issue #152 - animate login view presentation, ensure visibility

### PR DESCRIPTION
**Pull request by paulroub**
I was able to replicate the bug in the iPad 5.1 Simulator, but I don't have access to an physical 5.x device.

This clears up the issue under iOS 5, and logins still work as expected under iOS 6.

### CODE REVIEW

**Comment by ginatrapani** [comment]
Thanks for this fix, Paul. Testing in the iPhone 5.1 simulator, if I log into Dropbox one time everything works as expected. Then if I log out and attempt to log in again, the app crashes. I can repro this reliably in the simulator:

2012-11-15 01:00:28.978 Todo.txt Touch[7817:c07] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFDictionary setObject:forKey:]: attempt to insert nil value (key: WebKitLocalStorageDatabasePathPreferenceKey)'
**\* First throw call stack:
(0x17eb022 0x15bbcd6 0x1793a48 0x17939b9 0x17ea2da 0x356e93f 0x3572e15 0xba9714 0xba9b20 0x56a0d 0xab9a1e 0xab8fec 0xadff1d 0xaca1cb 0xae0df1 0xae0ea9 0xcda508 0xa97401 0xa9808b 0xcd9d6c 0xac0857 0xac09bc 0xac09fc 0x55dcc 0x55e13 0x1c8d6 0x1fc71 0x17ece99 0x9f514e 0x9f50e6 0xa9bade 0xa9bfa7 0xa9b266 0xa1a3c0 0xa1a5e6 0xa00dc4 0x9f4634 0x2303ef5 0x17bf195 0x1723ff2 0x17228da 0x1721d84 0x1721c9b 0x23027d8 0x230288a 0x9f2626 0x4f9d 0x2bd5)
terminate called throwing an exceptionsharedlibrary apply-load-rules all

Any ideas?

**Comment by paulroub** [comment]
Nothing jumps out at me - but I did confirm that it's not a _new_ issue.  I can reproduce the same error in the iPhone 5.1 sim with e24cb1c163955b9aa44515ed6c1c385541aa85f3 (the last rev before the rotation fix appeared).

We're dying somewhere in the process of setting up the Dropbox Login WebView.  I don't think I'll have time to investigate further until late tonight (EST) at the earliest.

**Comment by ginatrapani** [comment]
Ah! If it's not a new issue you're off the hook. Of course if you do have time to look at it tonight I'd appreciate it. I don't want to spend too much time/effort writing code for iOS5, but hopefully it's not a very involved fix.

Relatedly, I think my next focus is going to be setting up integration tests that automate these actions on the various simulators so I catch this stuff before we merge it. At some point I merged this bug and I shouldn't have.

Thanks again Paul.

**Comment by paulroub** [comment]
We're hitting an iOS 5.1 (only) bug.  Tested the workaround (from the StackOverflow post, linked in a comment) under the 5.1 simulator.  Clears things up, and still works fine under 6.0

**Comment by ginatrapani** [comment]
Excellent! This fix works in the 5.0 and 5.1 simulators here, as well as on my 6.0 device. I'm packaging up and submitting to Apple now. I don't think I can thank you enough for these recent fixes, you've been a tremendous help to the project. Let me know how I can return the favor. (Seriously!)

**Pull request merged**
